openapi: 3.0.0
info:
    title: PDF Processing API
    version: 1.0.0
paths:
    /upload:
        post:
            summary: Upload a PDF and if successful, get a unique document ID
            requestBody:
                required: true
                content:
                    application/pdf:
                        schema:
                            type: string
                            format: binary
            responses:
                '200':
                    description: PDF uploaded successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                                        description: Unique ID for the uploaded PDF
    /status/{id}:
        get:
            summary: Get processing status of the PDF, if processed, get tables with first 5 rows
            parameters:
                - in: path
                    name: id
                    required: true
                    schema:
                        type: string
                    description: Unique ID of the PDF
            responses:
                '200':
                    description: Processing status retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        enum: [processing, finished]
                                    progress:
                                        type: number
                                        description: Progress percentage
                                    tables:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: number
                                                caption:
                                                    type: string
                                                content:
                                                    type: string
                                                    description: HTML string with only the first 5 rows
                                                rowCount:
                                                    type: number
    /table/{id}:
        get:
            summary: Get content of a table, with all rows
            parameters:
                - in: path
                    name: id
                    required: true
                    schema:
                        type: number
                    description: ID of the table
            responses:
                '200':
                    description: Table content retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                    caption:
                                        type: string
                                    content:
                                        type: string
                                        description: HTML string with all rows
                                    rowCount:
                                        type: number
    /chat/{documentId}:
        get:
            summary: Get a new chat ID based on the provided document ID
            parameters:
                - in: path
                    name: documentId
                    required: true
                    schema:
                        type: string
                    description: Document ID
            responses:
                '200':
                    description: Chat ID retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    chatId:
                                        type: string
    /chat/query:
        post:
            summary: Submit a query and get a response
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                chatId:
                                    type: string
                                query:
                                    type: string
            responses:
                '200':
                    description: Query response retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    response:
                                        type: string